In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('files\lung_cancer_examples.csv')
df

           Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0          John         Wick   35       3      5       4       1
1          John  Constantine   27      20      2       5       1
2        Camela     Anderson   30       0      5       2       0
3          Alex       Telles   28       0      8       1       0
4         Diego     Maradona   68       4      5       6       1
5     Cristiano      Ronaldo   34       0     10       0       0
6        Mihail          Tal   58      15     10       0       0
7         Kathy        Bates   22      12      5       2       0
8        Nicole       Kidman   45       2      6       0       0
9           Ray      Milland   52      18      4       5       1
10      Fredric        March   33       4      8       0       0
11          Yul      Brynner   18      10      6       3       0
12         Joan     Crawford   25       2      5       1       0
13         Jane        Wyman   28      20      2       8       1
14         Anna      Magnani   34      25      4       8       1
15   Katharine       Hepburn   39      18      8       1       0
16   Katharine       Hepburn   42      22      3       5       1
17       Barbra    Streisand   19      12      8       0       0
18      Maggie         Smith   62       5      4       3       1
19      Glenda       Jackson   73      10      7       6       1
20        Jane         Fonda   55      15      1       3       1
21  Maximilian        Schell   33       8      8       1       0
22     Gregory          Peck   22      20      6       2       0
23      Sidney       Poitier   44       5      8       1       0
24         Rex      Harrison   77       3      2       6       1
25         Lee        Marvin   21      20      5       3       0
26        Paul      Scofield   37      15      6       2       0
27         Rod       Steiger   34      12      8       0       0
28        John         Wayne   55      20      1       4       1
29        Gene       Hackman   40      20      2       7       1
30      Marlon        Brando   36      13      5       2       0
31        Jack        Lemmon   56      20      3       3       1
32        Jack     Nicholson   47      15      1       8       1
33       Peter        Finch    62      25      3       4       1
34     Richard      Dreyfuss   26      10      7       2       0
35      Dustin       Hoffman   25      20      8       2       0
36       Henry        Henry    59      20      3       4       1
37      Robert        Duvall   62      15      5       5       1
38       Ellen       Burstyn   33      25      8       2       0
39        Faye       Dunaway   37      10      5       3       0
40       Diane        Keaton   50      20      2       4       1
41        Jane         Fonda   47      12      8       0       0
42       Sally         Field   69      20      5       4       1
43       Sissy        Spacek   63      20      4       5       1
44     Jessica         Lange   39      15      7       2       0
45     Gwyneth       Paltrow   21      20      8       3       0
46       Halle         Berry   31      20      9       4       0
47      Nicole        Kidman   28      10      4       1       0
48    Charlize        Theron   53      20      6       3       1
49   Katharine       Hepburn   62      20      5       6       1
50   Katharine       Hepburn   42      12      6       2       0
51      Barbra     Streisand   44      30      1       6       1
52      Maggie         Smith   26      34      1       8       1
53      Glenda       Jackson   35      20      5       1       0
54      Ernest      Borgnine   26      13      6       1       0
55        Alec      Guinness   77      20      5       4       1
56    Charlton        Heston   75      15      3       5       1
57     Gregory          Peck   43      30      3       8       1
58      Sidney       Poitier   51      25      9       0       0

In [2]:
df.size

413

In [3]:
df.head()

     Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    John         Wick   35       3      5       4       1
1    John  Constantine   27      20      2       5       1
2  Camela     Anderson   30       0      5       2       0
3    Alex       Telles   28       0      8       1       0
4   Diego     Maradona   68       4      5       6       1

In [4]:
df.isna().sum()

Name       0
Surname    0
Age        0
Smokes     0
AreaQ      0
Alkhol     0
Result     0
dtype: int64

In [8]:
x= df.iloc[:,2:-1].values
y = df.iloc[:,-1].values
y

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20)
x_train

array([[33,  4,  8,  0],
       [26, 13,  6,  1],
       [37, 15,  6,  2],
       [40, 20,  2,  7],
       [34, 25,  4,  8],
       [69, 20,  5,  4],
       [56, 20,  3,  3],
       [39, 18,  8,  1],
       [27, 20,  2,  5],
       [35,  3,  5,  4],
       [34,  0, 10,  0],
       [33,  8,  8,  1],
       [21, 20,  5,  3],
       [73, 10,  7,  6],
       [28, 10,  4,  1],
       [55, 15,  1,  3],
       [47, 12,  8,  0],
       [34, 12,  8,  0],
       [52, 18,  4,  5],
       [39, 15,  7,  2],
       [51, 25,  9,  0],
       [59, 20,  3,  4],
       [22, 12,  5,  2],
       [43, 30,  3,  8],
       [26, 34,  1,  8],
       [25,  2,  5,  1],
       [42, 22,  3,  5],
       [55, 20,  1,  4],
       [35, 20,  5,  1],
       [36, 13,  5,  2],
       [37, 10,  5,  3],
       [50, 20,  2,  4],
       [53, 20,  6,  3],
       [33, 25,  8,  2],
       [18, 10,  6,  3],
       [47, 15,  1,  8],
       [30,  0,  5,  2],
       [68,  4,  5,  6],
       [45,  2,  6,  0],
       [19, 12,  8,  0],
       [28, 20,  2,  8],
       [62, 25,  3,  4],
       [44,  5,  8,  1],
       [26, 10,  7,  2],
       [21, 20,  8,  3],
       [77,  3,  2,  6],
       [77, 20,  5,  4]], dtype=int64)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_train

array([[-0.53534471, -1.3526809 ,  1.22320431, -1.29998093],
       [-0.98695602, -0.22854726,  0.39000717, -0.89265357],
       [-0.27728111,  0.02126021,  0.39000717, -0.48532622],
       [-0.0837334 ,  0.6457789 , -1.27638711,  1.55131058],
       [-0.47082881,  1.27029758, -0.44318997,  1.95863794],
       [ 1.78722773,  0.6457789 , -0.0265914 ,  0.3293285 ],
       [ 0.94852101,  0.6457789 , -0.85978854, -0.07799886],
       [-0.1482493 ,  0.39597142,  1.22320431, -0.89265357],
       [-0.92244012,  0.6457789 , -1.27638711,  0.73665586],
       [-0.40631291, -1.47758463, -0.0265914 ,  0.3293285 ],
       [-0.47082881, -1.85229585,  2.05640145, -1.29998093],
       [-0.53534471, -0.85306595,  1.22320431, -0.89265357],
       [-1.30953552,  0.6457789 , -0.0265914 , -0.07799886],
       [ 2.04529133, -0.60325847,  0.80660574,  1.14398322],
       [-0.85792422, -0.60325847, -0.44318997, -0.89265357],
       [ 0.88400511,  0.02126021, -1.69298568, -0.07799886],
       [ 0.3678779 , -0.353451  ,  1.22320431, -1.29998093],
       [-0.47082881, -0.353451  ,  1.22320431, -1.29998093],
       [ 0.69045741,  0.39597142, -0.44318997,  0.73665586],
       [-0.1482493 ,  0.02126021,  0.80660574, -0.48532622],
       [ 0.62594151,  1.27029758,  1.63980288, -1.29998093],
       [ 1.14206872,  0.6457789 , -0.85978854,  0.3293285 ],
       [-1.24501962, -0.353451  , -0.0265914 , -0.48532622],
       [ 0.1098143 ,  1.89481627, -0.85978854,  1.95863794],
       [-0.98695602,  2.39443122, -1.69298568,  1.95863794],
       [-1.05147192, -1.60248837, -0.0265914 , -0.89265357],
       [ 0.0452984 ,  0.89558637, -0.85978854,  0.73665586],
       [ 0.88400511,  0.6457789 , -1.69298568,  0.3293285 ],
       [-0.40631291,  0.6457789 , -0.0265914 , -0.89265357],
       [-0.34179701, -0.22854726, -0.0265914 , -0.48532622],
       [-0.27728111, -0.60325847, -0.0265914 , -0.07799886],
       [ 0.56142561,  0.6457789 , -1.27638711,  0.3293285 ],
       [ 0.75497331,  0.6457789 ,  0.39000717, -0.07799886],
       [-0.53534471,  1.27029758,  1.22320431, -0.48532622],
       [-1.50308323, -0.60325847,  0.39000717, -0.07799886],
       [ 0.3678779 ,  0.02126021, -1.69298568,  1.95863794],
       [-0.72889241, -1.85229585, -0.0265914 , -0.48532622],
       [ 1.72271183, -1.3526809 , -0.0265914 ,  1.14398322],
       [ 0.2388461 , -1.60248837,  0.39000717, -1.29998093],
       [-1.43856733, -0.353451  ,  1.22320431, -1.29998093],
       [-0.85792422,  0.6457789 , -1.27638711,  1.95863794],
       [ 1.33561642,  1.27029758, -0.85978854,  0.3293285 ],
       [ 0.1743302 , -1.22777716,  1.22320431, -0.89265357],
       [-0.98695602, -0.60325847,  0.80660574, -0.48532622],
       [-1.30953552,  0.6457789 ,  1.22320431, -0.07799886],
       [ 2.30335494, -1.47758463, -1.27638711,  1.14398322],
       [ 2.30335494,  0.6457789 , -0.0265914 ,  0.3293285 ]])

### Naive Bayes

In [11]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
y_pred

array([1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0], dtype=int64)

In [12]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
mat = confusion_matrix(y_test,y_pred)
score = accuracy_score(y_test,y_pred)
score

1.0

### KNeighbors Classifier

In [14]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0], dtype=int64)

In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score
result = confusion_matrix(y_test,y_pred)
result

array([[6, 0],
       [0, 6]], dtype=int64)

In [17]:
score = accuracy_score(y_test,y_pred)
score

1.0